#:schema node_modules/wrangler/config-schema.json
# wrangler.toml is used for dev mode
# for production, use the cloudflare dashboard
# empty values are placeholders, replace them with your own values


name = "react-router-cf"
compatibility_date = "2025-03-11"
pages_build_output_dir = "./build/client"

[vars]
JWT_PRIVATE = """
(Insert private key here)
"""
JWT_PUBLIC = """
(Insert public key here)
"""


[[d1_databases]]
binding = "db"
database_name = ""
database_id = ""
