// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/providers": {
    params: {};
  };
  "/provider/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/providers" | "/provider/:id";
  };
  "routes/providers.tsx": {
    id: "routes/providers";
    page: "/providers";
  };
  "routes/provider.$id.tsx": {
    id: "routes/provider.$id";
    page: "/provider/:id";
  };
};